FROM mcr.microsoft.com/devcontainers/cpp:ubuntu-22.04

# RUN apt-get update \
#   apt-get upgrade -y \
#   \
#   sudo apt-get install -y --no-install-recommends software-properties-common \
#   \
#   echo "------------------------------" \
#   echo "Installing packages..." \
#   echo "------------------------------" \
#   #
#   pushd /tmp/ \
#   echo "Add CMake repo" \
#   wget https://apt.kitware.com/kitware-archive.sh \
#   chmod +x kitware-archive.sh \
#   sudo ./kitware-archive.sh \
#   \
#   popd \
#   sudo apt update \
#   \
#   echo "Install CMake" \
#   sudo apt install -y cmake \