
name: 'setup_cache'
description: 'sets up the shared cache'
inputs:
  compiler:
    required: true
    type: string
  build_type:
    required: true
    type: string
  generator:
    required: true
    type: string
  packaging_maintainer_mode:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          ~/.ccache
          "~/.local/share/powershell/Modules"
          ./_Out/build/vcpkg_installed
          ${{ env.VCPKG_DOWNLOADS}}
          ${{ env.VCPKG_ROOT}}/archives
          ${{ env.VCPKG_INSTALLATION_ROOT}}/archives
        key: ${{ runner.os }}-${{ inputs.compiler }}-${{ inputs.build_type }}-${{ inputs.generator }}-${{ inputs.packaging_maintainer_mode }}-${{ hashFiles('**/CMakeLists.txt') }}-${{ hashFiles('./vcpkg.json')}}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.compiler }}-${{ inputs.build_type }}

