name: ci
on:
  workflow_dispatch:
  pull_request:
  release:
    types: [published]
  push:
    branches:
      - main
      - dev

#env:

jobs:
  build-test:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ${{ matrix.platform.os }}
    env:
      CMAKE_PRESET: ${{matrix.platform.name}}-${{matrix.compiler}}-${{matrix.generator}}-${{matrix.build_type}}-${{matrix.build_kind}}
    strategy:
      fail-fast: false

      # CMake preset name template: "%Platform%-%Compiler%-%Generator%-%BuildType%-%BuildKind%"
      matrix:
        platform:
          - name: Linux
            os: ubuntu-latest
          - name: Windows
            os: windows-latest
        compiler:
          - Clang
          - Msvc
        generator:
          - Ninja
          - "Ninja Multi-Config"
          - Vs2022
        build_type:
          - Debug
          - Release
        build_kind:
          - Dev
          - QA
          - Shipping


    steps:
    - name: $CMAKE_PRESET
      run: echo "cmake preset $CMAKE_PRESET"

      # - uses: actions/checkout@v3

      # - name: Setup Cache
      #   uses: ./.github/actions/setup_cache
      #   with:
      #     compiler: ${{ matrix.compiler }}
      #     build_type: ${{ matrix.build_type }}
      #     packaging_maintainer_mode: ${{ matrix.packaging_maintainer_mode }}
      #     generator: ${{ matrix.generator }}


      # - name: CMake Configure
      #   run: |
      #     cmake --preset Linux-Clang-Ninja-Debug -DGIT_SHA:STRING=${{ github.sha }}

      #     # cmake -S . -B ./build -G "${{matrix.generator}}" -D${{ env.PROJECT_NAME }}_ENABLE_IPO=${{matrix.enable_ipo }} -DCMAKE_BUILD_TYPE:STRING=${{matrix.build_type}} -D${{ env.PROJECT_NAME }}_PACKAGING_MAINTAINER_MODE:BOOL=${{matrix.packaging_maintainer_mode}} -D${{ env.PROJECT_NAME }}_ENABLE_COVERAGE:BOOL=${{ matrix.build_type == 'Debug' }}

      # - name: CMake Build
      #   # Execute the build.  You can specify a specific target with "--target <NAME>"
      #   run: |
      #     cmake --build --preset Linux-Clang-Ninja-Debug